version: '3.9'

services:
    mysql:
        container_name: fastapi-graphql-db
        build: 
            context: ./mysql
            dockerfile: Dockerfile
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sample_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            TZ: 'Asia/Tokyo'
        volumes:
            - ./mysql/db:/docker-entrypoint-initdb.d  #初期データ
        ports:
            - '3306:3306'
    api:
        container_name: fastapi-graphql-api
        build: 
            context: ./api
            dockerfile: Dockerfile
        volumes:
          -  ./api:/app
        ports:
            - '8000:8000'
        tty: true
        links:
            - mysql